### PR TITLE
Expand Registry Documentation

### PR DESCRIPTION
**Pull request by birm**
While poking around some more, it seemed like a good idea to expand upon the registry documentation.

### CODE REVIEW

**Comment by birm** [comment]
Also, I can't seem to find any of the jobs/pipelines that jenkins uses for the builds in this repo; where do those live?

**Comment by zoq** [comment]
Inside the jenkins instance, I guess we could outsource the steps as well, in some cases it's just a single command, so not sure this is necessary.

**Comment by birm** [comment]
Okay, in that case, I think that's all I can do for the builds then. Pushing to dockerhub should then be a small addition, if that's desired, but I think that the existing registry is absolutely adequate.

**Review by rcurtin — APPROVED** [review]
This looks just fine to me, thanks for the updates. :+1:  I don't have mlpack-bot set up on this repo to auto-approve, but I'll wait until tomorrow and then merge in case there are any other comments.

**Review by zoq — APPROVED** [review]
Looks good to me.

**Comment by zoq** [comment]
Nice update, thanks!

**Pull request merged**
